name: Simply Grey
markdown: redcarpet
pygments: true
github: https://www.github.com/zhouzizi
about: I am an independent developer from the sunny UK. I dabble in Ruby, play in C and I'm an avid systems administrator.
urls:
    - text: github
      url: https://github.com/zhouzizi
    - text: email
      url: mailto:271460023@qq.com
